include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"

  errors:
    invalid_annotation_target: ignore
    todo: ignore
    depend_on_referenced_packages: ignore

# Regras extras (flutter_lints jรก inclui baseline). Mantidas as essenciais.
linter:
  rules:
    avoid_print: true
    avoid_relative_lib_imports: true
    use_build_context_synchronously: true
