include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
  
  errors:
    # Errors
    invalid_annotation_target: ignore
    todo: ignore
    
    # Warnings
    depend_on_referenced_packages: ignore

linter:
  rules:
    # Performance
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    
    # Code Quality
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - always_use_package_imports
    - avoid_relative_lib_imports
    
    # Null Safety
    - always_require_non_null_named_parameters
    - avoid_init_to_null
    - unnecessary_nullable_for_final_variable_declarations
    
    # Style
    - camel_case_types
    - library_names
    - file_names
    - non_constant_identifier_names
    - constant_identifier_names
    
    # Flutter Specific
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    
    # Avoid
    - avoid_empty_else
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    
    # Prefer
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
