// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHZPewIalqW9bTykCFPA4IoCIryxE3_vo',
    appId: '1:349397932778:web:f17c4fc8ff14fecb829593',
    messagingSenderId: '349397932778',
    projectId: 'renthus-cygc7s',
    authDomain: 'renthus-cygc7s.firebaseapp.com',
    storageBucket: 'renthus-cygc7s.firebasestorage.app',
    measurementId: 'G-TWDC3XRE2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95X1sqXsCSDA8LHukXz33yfPtRwoXS_0',
    appId: '1:349397932778:android:08a391bdcf2d6375829593',
    messagingSenderId: '349397932778',
    projectId: 'renthus-cygc7s',
    storageBucket: 'renthus-cygc7s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiazPqQrcyhJxwe9wjaLF6iKsfXOllQ2o',
    appId: '1:349397932778:ios:079075c83fdd5cb0829593',
    messagingSenderId: '349397932778',
    projectId: 'renthus-cygc7s',
    storageBucket: 'renthus-cygc7s.firebasestorage.app',
    iosBundleId: 'com.example.renthusNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiazPqQrcyhJxwe9wjaLF6iKsfXOllQ2o',
    appId: '1:349397932778:ios:079075c83fdd5cb0829593',
    messagingSenderId: '349397932778',
    projectId: 'renthus-cygc7s',
    storageBucket: 'renthus-cygc7s.firebasestorage.app',
    iosBundleId: 'com.example.renthusNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHZPewIalqW9bTykCFPA4IoCIryxE3_vo',
    appId: '1:349397932778:web:a2ee13052d61d0f7829593',
    messagingSenderId: '349397932778',
    projectId: 'renthus-cygc7s',
    authDomain: 'renthus-cygc7s.firebaseapp.com',
    storageBucket: 'renthus-cygc7s.firebasestorage.app',
    measurementId: 'G-22D0FJ0EXY',
  );
}
